<?php

$indicators = array(
	"economy"=>array(
		"local_economy_size",
		"local_economy_growth",
		"local_economy_structure",
		"safety_compliant_business",
		"increase_in_employment",
		"cost_of_living",
		"cost_of_doing_business",
		"financial_deepening",
		"productivity",
		"presence_of_business_and_professional",
	),
	"government_efficiency"=>array(
		"compliance_to_national_directives",
		"investment_promotion_unit",
		"registration_efficiency",
		"generate_local_resource",
		"capacity_of_health_services",
		"capacity_of_school_services",
		"recognition_of_performance",
		"business_permits_and_licensing",
		"peace_and_order",
		"social_protection",
	),
	"infrastructure"=>array(
		"road_network",
		"distance_to_ports",
		"availability_of_basic_utilities",
		"transportation_vehicles",
		"education",
		"health",
		"lgu_investment",
		"accommodation_capacity",
		"information_technology_capacity",
		"financial_technology_capacity",
	),
	"resiliency"=>array(
		"land_use_plan",
		"disaster_risk_reduction_plan",
		"annual_disaster_drill",
		"early_warning_system",
		"budget_for_drrmp",
		"local_risk_assessments",
		"emergency_infrastructure",
		"utilities",
		"employed_population",
		"sanitary_system",
	)
);

?>